import "./i18n";
import "./brick-tag";
import "./brick-timeline";
import "./brick-descriptions";
import "./brick-tree";
import "./brick-list";
import "./brick-table";
// !Lazy: import "./brick-code-display";
import "./brick-general-search";
import "./brick-button";
import "./brick-delete-confirm";
// !Lazy: import "./brick-collapse-card";
import "./brick-humanize-time";
import "./general-pagination";
// !Lazy: import "./statistic-card";
import "./brick-link";
// !Lazy: import "./brick-form";
// !Lazy: import "./markdown-editor";
import "./template-breadcrumb";
// !Lazy: import "./code-editor";
// !Lazy: import "./markdown-display";
import "./brick-input";
import "./brick-utils";
import "./brick-value-mapping";
import "./brick-cluster-type";
import "./brick-alert-level";
import "./brick-alert-value";
import "./brick-display-structs";
import "./brick-conditional-display";
import "./brick-collection-instance-execution";
import "./brick-alert-number";
import "./brick-user";
import "./cost-time";
import "./brick-alert-status";
import "./datetime-selector";
import "./brick-alert";
import "./brick-result";
// !Lazy: import "./card-item";
import "./dropdown-select";
import "./button-wrapper";
import "./general-list";
// !Lazy: import "./modal-confirm";
import "./brick-quick-entries";
import "./collapsible-card-item";
import "./single-field-edit";
import "./brick-placeholder";
import "./general-carousel";
import "./agent-status";
import "./dynamic-content";
import "./entry-card-item";
import "./general-video";
import "./log-display";
// !Lazy: import "./crontab-display";
import "./brick-divider";
import "./general-iframe";
import "./general-tooltip";
import "./general-transfer";
import "./general-label";
import "./basic-progress";
import "./copyable-text";
import "./brick-calendar";
import "./avatar-upload";
import "./general-badge";
import "./brick-rate";
import "./general-image";
import "./info-display-card-list";
import "./brick-illustration";
import "./dynamic-grid-container";
import "./general-slider";
import "./custom-processors/flattenTreeDataListAndCalcRowSpan";
import "./rank-table";
import "./dropdown-button";
import "./lazy-bricks";
import "./basic-icon";
import "./text-collapse";
import "./table-transfer";
