import "./i18n";
import "./custom-processors/getFlowConfigDagre";
import "./schema-editor";
import "./custom-processors/getNameSpaceTree";
import "./custom-processors/getNameSpaceCategory";
// !Lazy: import "./fields-mapping-editor";
import "./custom-processors/formatFeildsMap";
import "./lazy-bricks";
import "./data-providers/CreateFunctionContract";
import "./custom-processors/getFunctionStep";
import "./custom-processors/calcFlowInfo";
import "./custom-processors/processFieldInitValue";
