import {
  processGraphDataWithDiff,
  processFlattenDataWithDiff,
} from "./processDataWithDiff";

describe("processDataWithDiff", () => {
  it("processFlattenDataWithDiff should work", () => {
    expect(
      processFlattenDataWithDiff(
        [
          {
            _object_id: "STORYBOARD_FUNCTION",
            instanceId: "60ab601a2476d",
            name: "link",
            source: "function link() {\n  \n}\n",
            typescript: false,
            uuid: "9f8931b20fc0408892b8e41e334503de",
          },
          {
            _object_id: "STORYBOARD_FUNCTION",
            instanceId: "60ab962eb2659",
            name: "bbbb",
            source:
              "function bbbb(params: Params): Result {\n  11111;\n}\n\ninterface Params {}\n\ninterface Result {}\n",
            typescript: true,
            uuid: "ebb7f4d2195c4c76aa883bb627bd9477",
          },
          {
            _object_id: "STORYBOARD_FUNCTION",
            instanceId: "60ab99b8e5f85",
            name: "new",
            source:
              "function new(params: Params): Result {\n  \n}\n\ninterface Params {}\n\ninterface Result {}\n",
            typescript: true,
            uuid: "980ac99e8c404d4a9bf89b51a3184501",
          },
        ],
        {
          category: "functions",
          root: [
            {
              id: "ca67ffa2f62e4fa58de51af1ac5c0b7a",
              actions: [
                {
                  action: "delete",
                  originRootInstanceId: "",
                  curRootInstanceId: "",
                },
              ],
              dataOfId: "",
              changeDetail: [
                {
                  operation: "delete",
                  content:
                    '{"_object_id":"STORYBOARD_FUNCTION","ctime":"2023-11-22 16:19:59","name":"aaaa","source":"function aaaa() {\\n  \\n}\\n","tests":[],"typescript":false,"uuid":"ca67ffa2f62e4fa58de51af1ac5c0b7a"}',
                },
              ],
              children: [],
            },
            {
              id: "ebb7f4d2195c4c76aa883bb627bd9477",
              actions: [
                {
                  action: "modify",
                  originRootInstanceId: "",
                  curRootInstanceId: "",
                },
              ],
              dataOfId: "",
              changeDetail: [
                {
                  operation: "delete",
                  content:
                    '{"_object_id":"STORYBOARD_FUNCTION","ctime":"2023-11-22 16:20:05","name":"bbbb","source":"function bbbb(params: Params): Result {\\n  \\n}\\n\\ninterface Params {}\\n\\ninterface Result {}\\n","tests":[],"typescript":true,"uuid":"ebb7f4d2195c4c76aa883bb627bd9477"}',
                },
                {
                  operation: "insert",
                  content:
                    '{"_object_id":"STORYBOARD_FUNCTION","ctime":"2023-11-22 16:20:05","name":"bbbb","source":"function bbbb(params: Params): Result {\\n  11111;\\n}\\n\\ninterface Params {}\\n\\ninterface Result {}\\n","tests":[],"typescript":true,"uuid":"ebb7f4d2195c4c76aa883bb627bd9477"}',
                },
              ],
              children: [],
            },
            {
              id: "980ac99e8c404d4a9bf89b51a3184501",
              actions: [
                {
                  action: "add",
                  originRootInstanceId: "",
                  curRootInstanceId: "",
                },
              ],
              dataOfId: "",
              changeDetail: [
                {
                  operation: "insert",
                  content:
                    '{"_object_id":"STORYBOARD_FUNCTION","ctime":"2023-11-22 16:35:55","name":"new","source":"function new(params: Params): Result {\\n  \\n}\\n\\ninterface Params {}\\n\\ninterface Result {}\\n","tests":[],"typescript":true,"uuid":"980ac99e8c404d4a9bf89b51a3184501"}',
                },
              ],
              children: [],
            },
            {
              id: "9f8931b20fc0408892b8e41e334503de",
              actions: [
                {
                  action: "add",
                  originRootInstanceId: "",
                  curRootInstanceId: "",
                },
              ],
              dataOfId: "",
              changeDetail: [
                {
                  operation: "insert",
                  content:
                    '{"_object_id":"STORYBOARD_FUNCTION","ctime":"2023-11-22 12:18:08","name":"link","source":"function link() {\\n  \\n}\\n","tests":[],"typescript":false,"uuid":"9f8931b20fc0408892b8e41e334503de"}',
                },
              ],
              children: [],
            },
          ],
        },
        new Set()
      )
    ).toEqual([
      {
        _object_id: "STORYBOARD_FUNCTION",
        ctime: "2023-11-22 16:19:59",
        name: "aaaa",
        source: "function aaaa() {\n  \n}\n",
        tests: [],
        typescript: false,
        uuid: "ca67ffa2f62e4fa58de51af1ac5c0b7a",
      },
      {
        _object_id: "STORYBOARD_FUNCTION",
        ctime: "2023-11-22 16:20:05",
        name: "bbbb",
        source:
          "function bbbb(params: Params): Result {\n  \n}\n\ninterface Params {}\n\ninterface Result {}\n",
        tests: [],
        typescript: true,
        uuid: "ebb7f4d2195c4c76aa883bb627bd9477",
      },
    ]);
  });

  it("processGraphDataWithDiff should work", () => {
    expect(
      processGraphDataWithDiff(
        {
          topic_vertices: [
            {
              __label: ["B-44303"],
              _impl_from: [],
              _object_id: "STORYBOARD_ROUTE",
              _object_version: 18,
              _pre_ts: 1700641578,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700642415,
              _version: 2,
              alias: "bricks1111",
              analyticsData: null,
              appId: "test-commit-diff",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:18",
              defineResolves: null,
              deleteAuthorizers: [],
              documentId: null,
              exact: true,
              graphInfo: null,
              hybrid: false,
              id: "B-44303",
              if: null,
              instanceId: "60ab9792f9f0d",
              menu: null,
              modifier: "easyops",
              mountPoint: null,
              mtime: "2023-11-22 16:40:15",
              org: 8888,
              path: "${APP.homepage}/bricks1",
              permissionsPreCheck: null,
              previewSettings: null,
              providers: null,
              public: false,
              readAuthorizers: [],
              redirect: '""',
              screenshot: null,
              segues: null,
              sort: null,
              type: "bricks",
              updateAuthorizers: [],
              uuid: "33394a580e8a4f1682553ee8787a4cf1",
            },
            {
              __label: ["B-44308"],
              _impl_from: [],
              _object_id: "STORYBOARD_ROUTE",
              _object_version: 18,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641595,
              _version: 1,
              alias: "bricks2",
              analyticsData: null,
              appId: "test-commit-diff",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:35",
              defineResolves: null,
              deleteAuthorizers: [],
              documentId: null,
              exact: true,
              graphInfo: null,
              hybrid: false,
              id: "B-44308",
              if: null,
              instanceId: "60ab97a351e05",
              menu: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              path: "${APP.homepage}/bricks2",
              permissionsPreCheck: null,
              previewSettings: null,
              providers: null,
              public: false,
              readAuthorizers: [],
              redirect: null,
              screenshot: null,
              segues: null,
              sort: null,
              type: "bricks",
              updateAuthorizers: [],
              uuid: "d617fd39b0814cecb734712d8c1a0611",
            },
            {
              __label: ["B-44309"],
              _impl_from: [],
              _object_id: "STORYBOARD_ROUTE",
              _object_version: 18,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641605,
              _version: 1,
              alias: "routes",
              analyticsData: null,
              appId: "test-commit-diff",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:45",
              defineResolves: null,
              deleteAuthorizers: [],
              documentId: null,
              exact: false,
              graphInfo: null,
              hybrid: false,
              id: "B-44309",
              if: null,
              instanceId: "60ab97acfdf99",
              menu: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              path: "${APP.homepage}/routes",
              permissionsPreCheck: null,
              previewSettings: null,
              providers: null,
              public: false,
              readAuthorizers: [],
              redirect: null,
              screenshot: null,
              segues: null,
              sort: null,
              type: "routes",
              updateAuthorizers: [],
              uuid: "76c79225ff534da3b6ab8fab3d2c93ed",
            },
            {
              __label: ["B-44311"],
              _impl_from: [],
              _object_id: "STORYBOARD_ROUTE",
              _object_version: 18,
              _pre_ts: 1700641664,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700642398,
              _version: 3,
              alias: "redirect2",
              analyticsData: null,
              appId: "test-commit-diff",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:27:08",
              defineResolves: null,
              deleteAuthorizers: [],
              documentId: null,
              exact: true,
              graphInfo: null,
              hybrid: false,
              id: "B-44311",
              if: null,
              instanceId: "60ab97c270935",
              menu: '""',
              modifier: "easyops",
              mountPoint: null,
              mtime: "2023-11-22 16:39:58",
              org: 8888,
              path: "${APP.homepage}/routes/redirect2",
              permissionsPreCheck: null,
              previewSettings: null,
              providers: null,
              public: false,
              readAuthorizers: [],
              redirect: '"undefined"',
              screenshot: null,
              segues: null,
              sort: null,
              type: "redirect",
              updateAuthorizers: [],
              uuid: "a7ba9529de3b46828d0f25f9afe4ee92",
            },
          ],
          vertices: [
            {
              __label: ["B-44302"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641578,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "base-layout-v3.tpl-page-layout",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:18",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44302",
              if: null,
              injectDeep: true,
              instanceId: "60ab9792dc0ed",
              lifeCycle: null,
              modifier: null,
              mountPoint: "bricks",
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "showSidebar": false,\n  "menu": "<% APP.getMenu(\\"helloworld-menu\\") %>",\n  "bannerAlone": true,\n  "bannerTitle": "欢迎使用通栏布局",\n  "bannerDescription": "这里是描述",\n  "bannerImage": "<% `url(${IMG.get(\\"guideBanner11690875921519005722.png\\")})` %>"\n}',
              readAuthorizers: [],
              ref: null,
              sort: 1,
              type: "brick",
              updateAuthorizers: [],
              uuid: "a275e767c6a7443c85e8f401425bc7bd",
            },
            {
              __label: ["B-44307"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: 1700641595,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700642425,
              _version: 2,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "base-layout-v3.tpl-page-layout",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:35",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44307",
              if: null,
              injectDeep: true,
              instanceId: "60ab97a331fdd",
              lifeCycle: null,
              modifier: "easyops",
              mountPoint: "bricks",
              mtime: "2023-11-22 16:40:25",
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "pageTitle": "页面标题111",\n  "menu": "<% APP.getMenu(\\"helloworld-menu\\") %>",\n  "sidebarMenu": "<% APP.getMenu(\\"database-service-monitor-submenu\\") %>",\n  "subSidebarMenu": "<% APP.getMenu(\\"database-service-monitor-third-submenu\\") %>",\n  "showSubSidebar": true,\n  "breadcrumb": [\n    {\n      "text": "breadcrumb1",\n      "to": "breadcrumb"\n    },\n    {\n      "text": "breadcrumb2"\n    }\n  ]\n}',
              readAuthorizers: [],
              ref: null,
              sort: 1,
              type: "brick",
              updateAuthorizers: [],
              uuid: "82a3741113ff41a4a61c13ef76edb1e1",
            },
            {
              __label: ["B-44310"],
              _impl_from: [],
              _object_id: "STORYBOARD_ROUTE",
              _object_version: 18,
              _pre_ts: 1700641618,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700642407,
              _version: 2,
              alias: "redirect1",
              analyticsData: null,
              appId: "test-commit-diff",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:58",
              defineResolves: null,
              deleteAuthorizers: [],
              documentId: null,
              exact: true,
              graphInfo: null,
              hybrid: false,
              id: "B-44310",
              if: null,
              instanceId: "60ab97b92602d",
              menu: null,
              modifier: "easyops",
              mountPoint: null,
              mtime: "2023-11-22 16:40:07",
              org: 8888,
              path: "${APP.homepage}/redirect1",
              permissionsPreCheck: null,
              previewSettings: null,
              providers: null,
              public: false,
              readAuthorizers: [],
              redirect: '"undefined"',
              screenshot: null,
              segues: null,
              sort: null,
              type: "redirect",
              updateAuthorizers: [],
              uuid: "8a7568fe1b704ed18f99c3bd76e0454d",
            },
            {
              __label: ["B-44318"],
              _impl_from: [],
              _object_id: "STORYBOARD_ROUTE",
              _object_version: 18,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641652,
              _version: 1,
              alias: "bricks3",
              analyticsData: null,
              appId: "test-commit-diff",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:27:32",
              defineResolves: null,
              deleteAuthorizers: [],
              documentId: null,
              exact: true,
              graphInfo: null,
              hybrid: false,
              id: "B-44318",
              if: null,
              instanceId: "60ab97d9d36a9",
              menu: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              path: "${APP.homepage}/routes/bricks3",
              permissionsPreCheck: null,
              previewSettings: null,
              providers: null,
              public: false,
              readAuthorizers: [],
              redirect: null,
              screenshot: null,
              segues: null,
              sort: null,
              type: "bricks",
              updateAuthorizers: [],
              uuid: "558ad6a5a4a2407cae424103f0ad2c41",
            },
            {
              __label: ["B-44301"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641578,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-grid-layout",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:18",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44301",
              if: null,
              injectDeep: true,
              instanceId: "60ab9792d5c89",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties: null,
              readAuthorizers: [],
              ref: null,
              sort: 2,
              type: "brick",
              updateAuthorizers: [],
              uuid: "df7ae41f232045358075b97015da4da7",
            },
            {
              __label: ["B-44306"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641595,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-grid-layout",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:35",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44306",
              if: null,
              injectDeep: true,
              instanceId: "60ab97a326c2d",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties: null,
              readAuthorizers: [],
              ref: null,
              sort: 2,
              type: "brick",
              updateAuthorizers: [],
              uuid: "26b681d1796347ea809a68fc8bb90e36",
            },
            {
              __label: ["B-44317"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641652,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "base-layout-v3.tpl-page-layout",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:27:32",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44317",
              if: null,
              injectDeep: true,
              instanceId: "60ab97d9b6699",
              lifeCycle: null,
              modifier: null,
              mountPoint: "bricks",
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "showBreadcrumb": false,\n  "showSidebar": false,\n  "menu": "<% APP.getMenu(\\"helloworld-menu\\") %>",\n  "bannerAlone": true,\n  "bannerTitle": "欢迎使用通栏布局！",\n  "bannerImage": "<% `url(${IMG.get(\\"guideBanner11690875921519005722.png\\")})` %>"\n}',
              readAuthorizers: [],
              ref: null,
              sort: 1,
              type: "brick",
              updateAuthorizers: [],
              uuid: "92eda7d648c64bfba710e55637917b60",
            },
            {
              __label: ["B-44299"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641578,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-card",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:18",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44299",
              if: null,
              injectDeep: true,
              instanceId: "60ab9792cfb45",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
              readAuthorizers: [],
              ref: null,
              sort: 1,
              type: "brick",
              updateAuthorizers: [],
              uuid: "7c585a9436ee49b0add0525adcad599c",
            },
            {
              __label: ["B-44300"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641578,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-card",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:18",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44300",
              if: null,
              injectDeep: true,
              instanceId: "60ab9792cfe01",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
              readAuthorizers: [],
              ref: null,
              sort: 0,
              type: "brick",
              updateAuthorizers: [],
              uuid: "4ac2f42849da44e6bb56d349af58b92d",
            },
            {
              __label: ["B-44305"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641595,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-card",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:26:35",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44305",
              if: null,
              injectDeep: true,
              instanceId: "60ab97a31f6fd",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
              readAuthorizers: [],
              ref: null,
              sort: 0,
              type: "brick",
              updateAuthorizers: [],
              uuid: "22b27aa9c6ba4f819b2720c22923315e",
            },
            {
              __label: ["B-44315"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: 1700641652,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700642447,
              _version: 2,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-flex-layout",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:27:32",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44315",
              if: null,
              injectDeep: true,
              instanceId: "60ab97d9aeead",
              lifeCycle: null,
              modifier: "easyops",
              mountPoint: "banner",
              mtime: "2023-11-22 16:40:47",
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties: '{\n  "justifyContent": "center"\n}',
              readAuthorizers: [],
              ref: null,
              sort: 1,
              type: "brick",
              updateAuthorizers: [],
              uuid: "43aa036421fe4d30ad1b0b5f4612535f",
            },
            {
              __label: ["B-44316"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: 1700642447,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700642447,
              _version: 3,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-grid-layout",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:27:32",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44316",
              if: null,
              injectDeep: true,
              instanceId: "60ab97d9af0a1",
              lifeCycle: null,
              modifier: "easyops",
              mountPoint: "banner",
              mtime: "2023-11-22 16:40:47",
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties: null,
              readAuthorizers: [],
              ref: null,
              sort: 0,
              type: "brick",
              updateAuthorizers: [],
              uuid: "e5fa59da32de43f59849eaff3ff83e1b",
            },
            {
              __label: ["B-44319"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700642440,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: null,
              brick: "eo-button",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:40:40",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44319",
              if: null,
              injectDeep: true,
              instanceId: "60ab9ac8f868d",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties: null,
              readAuthorizers: [],
              ref: null,
              sort: 1,
              type: "brick",
              updateAuthorizers: [],
              uuid: "97fe08cad7154951bd295920f186cbdb",
            },
            {
              __label: ["B-44312"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641652,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-search",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:27:32",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44312",
              if: null,
              injectDeep: true,
              instanceId: "60ab97d99d8f1",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "placeholder": "搜索...",\n  "style": {\n    "width": "300px"\n  },\n  "dataset": {\n    "testid": "search"\n  }\n}',
              readAuthorizers: [],
              ref: null,
              sort: 1,
              type: "brick",
              updateAuthorizers: [],
              uuid: "b905370253464ee7bde109e18ceb987e",
            },
            {
              __label: ["B-44313"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641652,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-card",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:27:32",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44313",
              if: null,
              injectDeep: true,
              instanceId: "60ab97d9a6721",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
              readAuthorizers: [],
              ref: null,
              sort: 1,
              type: "brick",
              updateAuthorizers: [],
              uuid: "cde8015f4c8d4fac831f35579b9af9c7",
            },
            {
              __label: ["B-44314"],
              _impl_from: [],
              _object_id: "STORYBOARD_BRICK",
              _object_version: 16,
              _pre_ts: null,
              _tf_lineage: null,
              _tfstate: null,
              _ts: 1700641652,
              _version: 1,
              alias: null,
              appId: "test-commit-diff",
              bg: false,
              brick: "eo-card",
              context: null,
              creator: "easyops",
              ctime: "2023-11-22 16:27:32",
              dataSource: null,
              deleteAuthorizers: [],
              events: null,
              exports: null,
              id: "B-44314",
              if: null,
              injectDeep: true,
              instanceId: "60ab97d9a69dd",
              lifeCycle: null,
              modifier: null,
              mountPoint: null,
              mtime: null,
              org: 8888,
              params: null,
              permissionsPreCheck: null,
              portal: false,
              properties:
                '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
              readAuthorizers: [],
              ref: null,
              sort: 0,
              type: "brick",
              updateAuthorizers: [],
              uuid: "ccf49ea56a4947c58b4a3f2b5c2e26f5",
            },
          ],
          edges: [
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab9792f9f0d",
              in: "60ab9792dc0ed",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97a351e05",
              in: "60ab97a331fdd",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97acfdf99",
              in: "60ab97b92602d",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97acfdf99",
              in: "60ab97d9d36a9",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab9792dc0ed",
              in: "60ab9792d5c89",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97a331fdd",
              in: "60ab97a326c2d",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97d9d36a9",
              in: "60ab97d9b6699",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab9792d5c89",
              in: "60ab9792cfb45",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab9792d5c89",
              in: "60ab9792cfe01",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97a326c2d",
              in: "60ab97a31f6fd",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97d9b6699",
              in: "60ab97d9aeead",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97d9b6699",
              in: "60ab97d9af0a1",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97a326c2d",
              in: "60ab9ac8f868d",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97d9aeead",
              in: "60ab97d99d8f1",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97d9af0a1",
              in: "60ab97d9a6721",
              out_name: "children",
              properties: null,
            },
            {
              relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
              out: "60ab97d9af0a1",
              in: "60ab97d9a69dd",
              out_name: "children",
              properties: null,
            },
          ],
        },
        {
          category: "routes",
          root: [
            {
              id: "d617fd39b0814cecb734712d8c1a0611",
              actions: [],
              dataOfId:
                '{"_object_id":"STORYBOARD_ROUTE","alias":"bricks2","analyticsData":null,"appId":"test-commit-diff","context":null,"ctime":"2023-11-22 16:26:35","defineResolves":null,"documentId":null,"exact":true,"graphInfo":null,"hybrid":false,"if":null,"menu":null,"mountPoint":null,"path":"${APP.homepage}/bricks2","permissionsPreCheck":null,"previewSettings":null,"providers":null,"public":false,"redirect":null,"screenshot":null,"segues":null,"sort":null,"type":"bricks","uuid":"d617fd39b0814cecb734712d8c1a0611"}',
              changeDetail: [],
              children: [
                {
                  id: "82a3741113ff41a4a61c13ef76edb1e1",
                  actions: [
                    {
                      action: "modify",
                      originRootInstanceId: "",
                      curRootInstanceId: "",
                    },
                  ],
                  dataOfId: "",
                  changeDetail: [
                    {
                      operation: "delete",
                      content:
                        '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"base-layout-v3.tpl-page-layout","context":null,"ctime":"2023-11-22 16:26:35","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":"bricks","params":null,"permissionsPreCheck":null,"portal":false,"properties":"{\\n  \\"pageTitle\\": \\"页面标题\\",\\n  \\"menu\\": \\"<% APP.getMenu(\\\\\\"helloworld-menu\\\\\\") %>\\",\\n  \\"sidebarMenu\\": \\"<% APP.getMenu(\\\\\\"database-service-monitor-submenu\\\\\\") %>\\",\\n  \\"subSidebarMenu\\": \\"<% APP.getMenu(\\\\\\"database-service-monitor-third-submenu\\\\\\") %>\\",\\n  \\"showSubSidebar\\": true,\\n  \\"breadcrumb\\": [\\n    {\\n      \\"text\\": \\"breadcrumb1\\",\\n      \\"to\\": \\"breadcrumb\\"\\n    },\\n    {\\n      \\"text\\": \\"breadcrumb2\\"\\n    }\\n  ]\\n}","ref":null,"sort":1,"type":"brick","uuid":"82a3741113ff41a4a61c13ef76edb1e1"}',
                    },
                    {
                      operation: "insert",
                      content:
                        '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"base-layout-v3.tpl-page-layout","context":null,"ctime":"2023-11-22 16:26:35","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":"bricks","params":null,"permissionsPreCheck":null,"portal":false,"properties":"{\\n  \\"pageTitle\\": \\"页面标题 111\\",\\n  \\"menu\\": \\"<% APP.getMenu(\\\\\\"helloworld-menu\\\\\\") %>\\",\\n  \\"sidebarMenu\\": \\"<% APP.getMenu(\\\\\\"database-service-monitor-submenu\\\\\\") %>\\",\\n  \\"subSidebarMenu\\": \\"<% APP.getMenu(\\\\\\"database-service-monitor-third-submenu\\\\\\") %>\\",\\n  \\"showSubSidebar\\": true,\\n  \\"breadcrumb\\": [\\n    {\\n      \\"text\\": \\"breadcrumb1\\",\\n      \\"to\\": \\"breadcrumb\\"\\n    },\\n    {\\n      \\"text\\": \\"breadcrumb2\\"\\n    }\\n  ]\\n}","ref":null,"sort":1,"type":"brick","uuid":"82a3741113ff41a4a61c13ef76edb1e1"}',
                    },
                  ],
                  children: [
                    {
                      id: "26b681d1796347ea809a68fc8bb90e36",
                      actions: [],
                      dataOfId:
                        '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"eo-grid-layout","context":null,"ctime":"2023-11-22 16:26:35","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":null,"params":null,"permissionsPreCheck":null,"portal":false,"properties":null,"ref":null,"sort":2,"type":"brick","uuid":"26b681d1796347ea809a68fc8bb90e36"}',
                      changeDetail: [],
                      children: [
                        {
                          id: "97fe08cad7154951bd295920f186cbdb",
                          actions: [
                            {
                              action: "add",
                              originRootInstanceId: "",
                              curRootInstanceId: "",
                            },
                          ],
                          dataOfId: "",
                          changeDetail: [
                            {
                              operation: "insert",
                              content:
                                '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":null,"brick":"eo-button","context":null,"ctime":"2023-11-22 16:40:40","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":null,"params":null,"permissionsPreCheck":null,"portal":false,"properties":null,"ref":null,"sort":1,"type":"brick","uuid":"97fe08cad7154951bd295920f186cbdb"}',
                            },
                          ],
                          children: [],
                        },
                        {
                          id: "a25b36626d054a9180b8674de968b6ca",
                          actions: [
                            {
                              action: "delete",
                              originRootInstanceId: "",
                              curRootInstanceId: "",
                            },
                          ],
                          dataOfId: "",
                          changeDetail: [
                            {
                              operation: "delete",
                              content:
                                '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"eo-card","context":null,"ctime":"2023-11-22 16:26:35","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":null,"params":null,"permissionsPreCheck":null,"portal":false,"properties":"{\\n  \\"cardTitle\\": \\"卡片标题\\",\\n  \\"textContent\\": \\"卡片内容\\",\\n  \\"dataset\\": {\\n    \\"testid\\": \\"card\\"\\n  }\\n}","ref":null,"sort":1,"type":"brick","uuid":"a25b36626d054a9180b8674de968b6ca"}',
                            },
                          ],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: "76c79225ff534da3b6ab8fab3d2c93ed",
              actions: [],
              dataOfId:
                '{"_object_id":"STORYBOARD_ROUTE","alias":"routes","analyticsData":null,"appId":"test-commit-diff","context":null,"ctime":"2023-11-22 16:26:45","defineResolves":null,"documentId":null,"exact":false,"graphInfo":null,"hybrid":false,"if":null,"menu":null,"mountPoint":null,"path":"${APP.homepage}/routes","permissionsPreCheck":null,"previewSettings":null,"providers":null,"public":false,"redirect":null,"screenshot":null,"segues":null,"sort":null,"type":"routes","uuid":"76c79225ff534da3b6ab8fab3d2c93ed"}',
              changeDetail: [],
              children: [
                {
                  id: "558ad6a5a4a2407cae424103f0ad2c41",
                  actions: [],
                  dataOfId:
                    '{"_object_id":"STORYBOARD_ROUTE","alias":"bricks3","analyticsData":null,"appId":"test-commit-diff","context":null,"ctime":"2023-11-22 16:27:32","defineResolves":null,"documentId":null,"exact":true,"graphInfo":null,"hybrid":false,"if":null,"menu":null,"mountPoint":null,"path":"${APP.homepage}/routes/bricks3","permissionsPreCheck":null,"previewSettings":null,"providers":null,"public":false,"redirect":null,"screenshot":null,"segues":null,"sort":null,"type":"bricks","uuid":"558ad6a5a4a2407cae424103f0ad2c41"}',
                  changeDetail: [],
                  children: [
                    {
                      id: "92eda7d648c64bfba710e55637917b60",
                      actions: [],
                      dataOfId:
                        '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"base-layout-v3.tpl-page-layout","context":null,"ctime":"2023-11-22 16:27:32","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":"bricks","params":null,"permissionsPreCheck":null,"portal":false,"properties":"{\\n  \\"showBreadcrumb\\": false,\\n  \\"showSidebar\\": false,\\n  \\"menu\\": \\"<% APP.getMenu(\\\\\\"helloworld-menu\\\\\\") %>\\",\\n  \\"bannerAlone\\": true,\\n  \\"bannerTitle\\": \\"欢迎使用通栏布局！\\",\\n  \\"bannerImage\\": \\"<% `url(${IMG.get(\\\\\\"guideBanner11690875921519005722.png\\\\\\")})` %>\\"\\n}","ref":null,"sort":1,"type":"brick","uuid":"92eda7d648c64bfba710e55637917b60"}',
                      changeDetail: [],
                      children: [
                        {
                          id: "43aa036421fe4d30ad1b0b5f4612535f",
                          actions: [
                            {
                              action: "modify",
                              originRootInstanceId: "",
                              curRootInstanceId: "",
                            },
                          ],
                          dataOfId: "",
                          changeDetail: [
                            {
                              operation: "delete",
                              content:
                                '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"eo-flex-layout","context":null,"ctime":"2023-11-22 16:27:32","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":"banner","params":null,"permissionsPreCheck":null,"portal":false,"properties":"{\\n  \\"justifyContent\\": \\"center\\"\\n}","ref":null,"sort":2,"type":"brick","uuid":"43aa036421fe4d30ad1b0b5f4612535f"}',
                            },
                            {
                              operation: "insert",
                              content:
                                '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"eo-flex-layout","context":null,"ctime":"2023-11-22 16:27:32","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":"banner","params":null,"permissionsPreCheck":null,"portal":false,"properties":"{\\n  \\"justifyContent\\": \\"center\\"\\n}","ref":null,"sort":1,"type":"brick","uuid":"43aa036421fe4d30ad1b0b5f4612535f"}',
                            },
                          ],
                          children: [],
                        },
                        {
                          id: "e5fa59da32de43f59849eaff3ff83e1b",
                          actions: [
                            {
                              action: "modify",
                              originRootInstanceId: "",
                              curRootInstanceId: "",
                            },
                          ],
                          dataOfId: "",
                          changeDetail: [
                            {
                              operation: "delete",
                              content:
                                '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"eo-grid-layout","context":null,"ctime":"2023-11-22 16:27:32","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":null,"params":null,"permissionsPreCheck":null,"portal":false,"properties":null,"ref":null,"sort":2,"type":"brick","uuid":"e5fa59da32de43f59849eaff3ff83e1b"}',
                            },
                            {
                              operation: "insert",
                              content:
                                '{"_object_id":"STORYBOARD_BRICK","alias":null,"appId":"test-commit-diff","bg":false,"brick":"eo-grid-layout","context":null,"ctime":"2023-11-22 16:27:32","dataSource":null,"events":null,"exports":null,"if":null,"injectDeep":true,"lifeCycle":null,"mountPoint":"banner","params":null,"permissionsPreCheck":null,"portal":false,"properties":null,"ref":null,"sort":0,"type":"brick","uuid":"e5fa59da32de43f59849eaff3ff83e1b"}',
                            },
                          ],
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "8a7568fe1b704ed18f99c3bd76e0454d",
                  actions: [
                    {
                      action: "move",
                      originRootInstanceId: "",
                      curRootInstanceId: "76c79225ff534da3b6ab8fab3d2c93ed",
                    },
                  ],
                  dataOfId:
                    '{"_object_id":"STORYBOARD_ROUTE","alias":"redirect1","analyticsData":null,"appId":"test-commit-diff","context":null,"ctime":"2023-11-22 16:26:58","defineResolves":null,"documentId":null,"exact":true,"graphInfo":null,"hybrid":false,"if":null,"menu":null,"mountPoint":null,"path":"${APP.homepage}/redirect1","permissionsPreCheck":null,"previewSettings":null,"providers":null,"public":false,"redirect":"\\"undefined\\"","screenshot":null,"segues":null,"sort":null,"type":"redirect","uuid":"8a7568fe1b704ed18f99c3bd76e0454d"}',
                  changeDetail: [],
                  children: [],
                },
                {
                  id: "a7ba9529de3b46828d0f25f9afe4ee92",
                  actions: [
                    {
                      action: "move",
                      originRootInstanceId: "76c79225ff534da3b6ab8fab3d2c93ed",
                      curRootInstanceId: "",
                    },
                  ],
                  dataOfId:
                    '{"_object_id":"STORYBOARD_ROUTE","alias":"redirect2","analyticsData":null,"appId":"test-commit-diff","context":null,"ctime":"2023-11-22 16:27:08","defineResolves":null,"documentId":null,"exact":true,"graphInfo":null,"hybrid":false,"if":null,"menu":"\\"\\"","mountPoint":null,"path":"${APP.homepage}/routes/redirect2","permissionsPreCheck":null,"previewSettings":null,"providers":null,"public":false,"redirect":"\\"undefined\\"","screenshot":null,"segues":null,"sort":null,"type":"redirect","uuid":"a7ba9529de3b46828d0f25f9afe4ee92"}',
                  changeDetail: [],
                  children: [],
                },
              ],
            },
            {
              id: "33394a580e8a4f1682553ee8787a4cf1",
              actions: [
                {
                  action: "modify",
                  originRootInstanceId: "",
                  curRootInstanceId: "",
                },
              ],
              dataOfId: "",
              changeDetail: [
                {
                  operation: "delete",
                  content:
                    '{"_object_id":"STORYBOARD_ROUTE","alias":"bricks1","analyticsData":null,"appId":"test-commit-diff","context":null,"ctime":"2023-11-22 16:26:18","defineResolves":null,"documentId":null,"exact":true,"graphInfo":null,"hybrid":false,"if":null,"menu":null,"mountPoint":null,"path":"${APP.homepage}/bricks1","permissionsPreCheck":null,"previewSettings":null,"providers":null,"public":false,"redirect":null,"screenshot":null,"segues":null,"sort":null,"type":"bricks","uuid":"33394a580e8a4f1682553ee8787a4cf1"}',
                },
                {
                  operation: "insert",
                  content:
                    '{"_object_id":"STORYBOARD_ROUTE","alias":"bricks1111","analyticsData":null,"appId":"test-commit-diff","context":null,"ctime":"2023-11-22 16:26:18","defineResolves":null,"documentId":null,"exact":true,"graphInfo":null,"hybrid":false,"if":null,"menu":null,"mountPoint":null,"path":"${APP.homepage}/bricks1","permissionsPreCheck":null,"previewSettings":null,"providers":null,"public":false,"redirect":"\\"\\"","screenshot":null,"segues":null,"sort":null,"type":"bricks","uuid":"33394a580e8a4f1682553ee8787a4cf1"}',
                },
              ],
              children: [],
            },
            {
              id: "a7ba9529de3b46828d0f25f9afe4ee92",
              actions: [
                {
                  action: "move",
                  originRootInstanceId: "76c79225ff534da3b6ab8fab3d2c93ed",
                  curRootInstanceId: "",
                },
              ],
              dataOfId:
                '{"_object_id":"STORYBOARD_ROUTE","alias":"redirect2","analyticsData":null,"appId":"test-commit-diff","context":null,"ctime":"2023-11-22 16:27:08","defineResolves":null,"documentId":null,"exact":true,"graphInfo":null,"hybrid":false,"if":null,"menu":"\\"\\"","mountPoint":null,"path":"${APP.homepage}/routes/redirect2","permissionsPreCheck":null,"previewSettings":null,"providers":null,"public":false,"redirect":"\\"undefined\\"","screenshot":null,"segues":null,"sort":null,"type":"redirect","uuid":"a7ba9529de3b46828d0f25f9afe4ee92"}',
              changeDetail: [],
              children: [],
            },
          ],
        },
        new Set()
      )
    ).toEqual({
      topic_vertices: [
        {
          _object_id: "STORYBOARD_ROUTE",
          alias: "redirect1",
          analyticsData: null,
          appId: "test-commit-diff",
          context: null,
          ctime: "2023-11-22 16:26:58",
          defineResolves: null,
          documentId: null,
          exact: true,
          graphInfo: null,
          hybrid: false,
          if: null,
          menu: null,
          mountPoint: null,
          path: "${APP.homepage}/redirect1",
          permissionsPreCheck: null,
          previewSettings: null,
          providers: null,
          public: false,
          redirect: '"undefined"',
          screenshot: null,
          segues: null,
          sort: null,
          type: "redirect",
          uuid: "8a7568fe1b704ed18f99c3bd76e0454d",
        },
        {
          _object_id: "STORYBOARD_ROUTE",
          alias: "bricks1",
          analyticsData: null,
          appId: "test-commit-diff",
          context: null,
          ctime: "2023-11-22 16:26:18",
          defineResolves: null,
          documentId: null,
          exact: true,
          graphInfo: null,
          hybrid: false,
          if: null,
          menu: null,
          mountPoint: null,
          path: "${APP.homepage}/bricks1",
          permissionsPreCheck: null,
          previewSettings: null,
          providers: null,
          public: false,
          redirect: null,
          screenshot: null,
          segues: null,
          sort: null,
          type: "bricks",
          uuid: "33394a580e8a4f1682553ee8787a4cf1",
        },
        {
          __label: ["B-44308"],
          _impl_from: [],
          _object_id: "STORYBOARD_ROUTE",
          _object_version: 18,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641595,
          _version: 1,
          alias: "bricks2",
          analyticsData: null,
          appId: "test-commit-diff",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:26:35",
          defineResolves: null,
          deleteAuthorizers: [],
          documentId: null,
          exact: true,
          graphInfo: null,
          hybrid: false,
          id: "B-44308",
          if: null,
          instanceId: "60ab97a351e05",
          menu: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          path: "${APP.homepage}/bricks2",
          permissionsPreCheck: null,
          previewSettings: null,
          providers: null,
          public: false,
          readAuthorizers: [],
          redirect: null,
          screenshot: null,
          segues: null,
          sort: null,
          type: "bricks",
          updateAuthorizers: [],
          uuid: "d617fd39b0814cecb734712d8c1a0611",
        },
        {
          __label: ["B-44309"],
          _impl_from: [],
          _object_id: "STORYBOARD_ROUTE",
          _object_version: 18,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641605,
          _version: 1,
          alias: "routes",
          analyticsData: null,
          appId: "test-commit-diff",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:26:45",
          defineResolves: null,
          deleteAuthorizers: [],
          documentId: null,
          exact: false,
          graphInfo: null,
          hybrid: false,
          id: "B-44309",
          if: null,
          instanceId: "60ab97acfdf99",
          menu: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          path: "${APP.homepage}/routes",
          permissionsPreCheck: null,
          previewSettings: null,
          providers: null,
          public: false,
          readAuthorizers: [],
          redirect: null,
          screenshot: null,
          segues: null,
          sort: null,
          type: "routes",
          updateAuthorizers: [],
          uuid: "76c79225ff534da3b6ab8fab3d2c93ed",
        },
      ],
      vertices: [
        {
          _object_id: "STORYBOARD_BRICK",
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-card",
          context: null,
          ctime: "2023-11-22 16:26:35",
          dataSource: null,
          events: null,
          exports: null,
          if: null,
          injectDeep: true,
          lifeCycle: null,
          mountPoint: null,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
          ref: null,
          sort: 1,
          type: "brick",
          uuid: "a25b36626d054a9180b8674de968b6ca",
        },
        {
          _object_id: "STORYBOARD_ROUTE",
          alias: "redirect2",
          analyticsData: null,
          appId: "test-commit-diff",
          context: null,
          ctime: "2023-11-22 16:27:08",
          defineResolves: null,
          documentId: null,
          exact: true,
          graphInfo: null,
          hybrid: false,
          if: null,
          menu: '""',
          mountPoint: null,
          path: "${APP.homepage}/routes/redirect2",
          permissionsPreCheck: null,
          previewSettings: null,
          providers: null,
          public: false,
          redirect: '"undefined"',
          screenshot: null,
          segues: null,
          sort: null,
          type: "redirect",
          uuid: "a7ba9529de3b46828d0f25f9afe4ee92",
        },
        {
          __label: ["B-44302"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641578,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "base-layout-v3.tpl-page-layout",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:26:18",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44302",
          if: null,
          injectDeep: true,
          instanceId: "60ab9792dc0ed",
          lifeCycle: null,
          modifier: null,
          mountPoint: "bricks",
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "showSidebar": false,\n  "menu": "<% APP.getMenu(\\"helloworld-menu\\") %>",\n  "bannerAlone": true,\n  "bannerTitle": "欢迎使用通栏布局",\n  "bannerDescription": "这里是描述",\n  "bannerImage": "<% `url(${IMG.get(\\"guideBanner11690875921519005722.png\\")})` %>"\n}',
          readAuthorizers: [],
          ref: null,
          sort: 1,
          type: "brick",
          updateAuthorizers: [],
          uuid: "a275e767c6a7443c85e8f401425bc7bd",
        },
        {
          _object_id: "STORYBOARD_BRICK",
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "base-layout-v3.tpl-page-layout",
          context: null,
          ctime: "2023-11-22 16:26:35",
          dataSource: null,
          events: null,
          exports: null,
          if: null,
          injectDeep: true,
          lifeCycle: null,
          mountPoint: "bricks",
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "pageTitle": "页面标题",\n  "menu": "<% APP.getMenu(\\"helloworld-menu\\") %>",\n  "sidebarMenu": "<% APP.getMenu(\\"database-service-monitor-submenu\\") %>",\n  "subSidebarMenu": "<% APP.getMenu(\\"database-service-monitor-third-submenu\\") %>",\n  "showSubSidebar": true,\n  "breadcrumb": [\n    {\n      "text": "breadcrumb1",\n      "to": "breadcrumb"\n    },\n    {\n      "text": "breadcrumb2"\n    }\n  ]\n}',
          ref: null,
          sort: 1,
          type: "brick",
          uuid: "82a3741113ff41a4a61c13ef76edb1e1",
        },
        {
          __label: ["B-44318"],
          _impl_from: [],
          _object_id: "STORYBOARD_ROUTE",
          _object_version: 18,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641652,
          _version: 1,
          alias: "bricks3",
          analyticsData: null,
          appId: "test-commit-diff",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:27:32",
          defineResolves: null,
          deleteAuthorizers: [],
          documentId: null,
          exact: true,
          graphInfo: null,
          hybrid: false,
          id: "B-44318",
          if: null,
          instanceId: "60ab97d9d36a9",
          menu: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          path: "${APP.homepage}/routes/bricks3",
          permissionsPreCheck: null,
          previewSettings: null,
          providers: null,
          public: false,
          readAuthorizers: [],
          redirect: null,
          screenshot: null,
          segues: null,
          sort: null,
          type: "bricks",
          updateAuthorizers: [],
          uuid: "558ad6a5a4a2407cae424103f0ad2c41",
        },
        {
          __label: ["B-44301"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641578,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-grid-layout",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:26:18",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44301",
          if: null,
          injectDeep: true,
          instanceId: "60ab9792d5c89",
          lifeCycle: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties: null,
          readAuthorizers: [],
          ref: null,
          sort: 2,
          type: "brick",
          updateAuthorizers: [],
          uuid: "df7ae41f232045358075b97015da4da7",
        },
        {
          __label: ["B-44306"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641595,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-grid-layout",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:26:35",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44306",
          if: null,
          injectDeep: true,
          instanceId: "60ab97a326c2d",
          lifeCycle: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties: null,
          readAuthorizers: [],
          ref: null,
          sort: 2,
          type: "brick",
          updateAuthorizers: [],
          uuid: "26b681d1796347ea809a68fc8bb90e36",
        },
        {
          __label: ["B-44317"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641652,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "base-layout-v3.tpl-page-layout",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:27:32",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44317",
          if: null,
          injectDeep: true,
          instanceId: "60ab97d9b6699",
          lifeCycle: null,
          modifier: null,
          mountPoint: "bricks",
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "showBreadcrumb": false,\n  "showSidebar": false,\n  "menu": "<% APP.getMenu(\\"helloworld-menu\\") %>",\n  "bannerAlone": true,\n  "bannerTitle": "欢迎使用通栏布局！",\n  "bannerImage": "<% `url(${IMG.get(\\"guideBanner11690875921519005722.png\\")})` %>"\n}',
          readAuthorizers: [],
          ref: null,
          sort: 1,
          type: "brick",
          updateAuthorizers: [],
          uuid: "92eda7d648c64bfba710e55637917b60",
        },
        {
          __label: ["B-44299"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641578,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-card",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:26:18",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44299",
          if: null,
          injectDeep: true,
          instanceId: "60ab9792cfb45",
          lifeCycle: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
          readAuthorizers: [],
          ref: null,
          sort: 1,
          type: "brick",
          updateAuthorizers: [],
          uuid: "7c585a9436ee49b0add0525adcad599c",
        },
        {
          __label: ["B-44300"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641578,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-card",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:26:18",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44300",
          if: null,
          injectDeep: true,
          instanceId: "60ab9792cfe01",
          lifeCycle: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
          readAuthorizers: [],
          ref: null,
          sort: 0,
          type: "brick",
          updateAuthorizers: [],
          uuid: "4ac2f42849da44e6bb56d349af58b92d",
        },
        {
          __label: ["B-44305"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641595,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-card",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:26:35",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44305",
          if: null,
          injectDeep: true,
          instanceId: "60ab97a31f6fd",
          lifeCycle: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
          readAuthorizers: [],
          ref: null,
          sort: 0,
          type: "brick",
          updateAuthorizers: [],
          uuid: "22b27aa9c6ba4f819b2720c22923315e",
        },
        {
          _object_id: "STORYBOARD_BRICK",
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-flex-layout",
          context: null,
          ctime: "2023-11-22 16:27:32",
          dataSource: null,
          events: null,
          exports: null,
          if: null,
          injectDeep: true,
          lifeCycle: null,
          mountPoint: "banner",
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties: '{\n  "justifyContent": "center"\n}',
          ref: null,
          sort: 2,
          type: "brick",
          uuid: "43aa036421fe4d30ad1b0b5f4612535f",
        },
        {
          _object_id: "STORYBOARD_BRICK",
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-grid-layout",
          context: null,
          ctime: "2023-11-22 16:27:32",
          dataSource: null,
          events: null,
          exports: null,
          if: null,
          injectDeep: true,
          lifeCycle: null,
          mountPoint: null,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties: null,
          ref: null,
          sort: 2,
          type: "brick",
          uuid: "e5fa59da32de43f59849eaff3ff83e1b",
        },
        {
          __label: ["B-44312"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641652,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-search",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:27:32",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44312",
          if: null,
          injectDeep: true,
          instanceId: "60ab97d99d8f1",
          lifeCycle: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "placeholder": "搜索...",\n  "style": {\n    "width": "300px"\n  },\n  "dataset": {\n    "testid": "search"\n  }\n}',
          readAuthorizers: [],
          ref: null,
          sort: 1,
          type: "brick",
          updateAuthorizers: [],
          uuid: "b905370253464ee7bde109e18ceb987e",
        },
        {
          __label: ["B-44313"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641652,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-card",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:27:32",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44313",
          if: null,
          injectDeep: true,
          instanceId: "60ab97d9a6721",
          lifeCycle: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
          readAuthorizers: [],
          ref: null,
          sort: 1,
          type: "brick",
          updateAuthorizers: [],
          uuid: "cde8015f4c8d4fac831f35579b9af9c7",
        },
        {
          __label: ["B-44314"],
          _impl_from: [],
          _object_id: "STORYBOARD_BRICK",
          _object_version: 16,
          _pre_ts: null,
          _tf_lineage: null,
          _tfstate: null,
          _ts: 1700641652,
          _version: 1,
          alias: null,
          appId: "test-commit-diff",
          bg: false,
          brick: "eo-card",
          context: null,
          creator: "easyops",
          ctime: "2023-11-22 16:27:32",
          dataSource: null,
          deleteAuthorizers: [],
          events: null,
          exports: null,
          id: "B-44314",
          if: null,
          injectDeep: true,
          instanceId: "60ab97d9a69dd",
          lifeCycle: null,
          modifier: null,
          mountPoint: null,
          mtime: null,
          org: 8888,
          params: null,
          permissionsPreCheck: null,
          portal: false,
          properties:
            '{\n  "cardTitle": "卡片标题",\n  "textContent": "卡片内容",\n  "dataset": {\n    "testid": "card"\n  }\n}',
          readAuthorizers: [],
          ref: null,
          sort: 0,
          type: "brick",
          updateAuthorizers: [],
          uuid: "ccf49ea56a4947c58b4a3f2b5c2e26f5",
        },
      ],
      edges: [
        {
          out: "26b681d1796347ea809a68fc8bb90e36",
          in: "a25b36626d054a9180b8674de968b6ca",
          out_name: "children",
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "33394a580e8a4f1682553ee8787a4cf1",
          in: "a275e767c6a7443c85e8f401425bc7bd",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "d617fd39b0814cecb734712d8c1a0611",
          in: "82a3741113ff41a4a61c13ef76edb1e1",
          out_name: "children",
          properties: null,
        },
        {
          out: "",
          in: "8a7568fe1b704ed18f99c3bd76e0454d",
          out_name: "children",
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "76c79225ff534da3b6ab8fab3d2c93ed",
          in: "558ad6a5a4a2407cae424103f0ad2c41",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "a275e767c6a7443c85e8f401425bc7bd",
          in: "df7ae41f232045358075b97015da4da7",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "82a3741113ff41a4a61c13ef76edb1e1",
          in: "26b681d1796347ea809a68fc8bb90e36",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "558ad6a5a4a2407cae424103f0ad2c41",
          in: "92eda7d648c64bfba710e55637917b60",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "df7ae41f232045358075b97015da4da7",
          in: "7c585a9436ee49b0add0525adcad599c",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "df7ae41f232045358075b97015da4da7",
          in: "4ac2f42849da44e6bb56d349af58b92d",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "26b681d1796347ea809a68fc8bb90e36",
          in: "22b27aa9c6ba4f819b2720c22923315e",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "92eda7d648c64bfba710e55637917b60",
          in: "43aa036421fe4d30ad1b0b5f4612535f",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "92eda7d648c64bfba710e55637917b60",
          in: "e5fa59da32de43f59849eaff3ff83e1b",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "43aa036421fe4d30ad1b0b5f4612535f",
          in: "b905370253464ee7bde109e18ceb987e",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "e5fa59da32de43f59849eaff3ff83e1b",
          in: "cde8015f4c8d4fac831f35579b9af9c7",
          out_name: "children",
          properties: null,
        },
        {
          relation_id: "STORYBOARD_NODE_children_parent_STORYBOARD_NODE",
          out: "e5fa59da32de43f59849eaff3ff83e1b",
          in: "ccf49ea56a4947c58b4a3f2b5c2e26f5",
          out_name: "children",
          properties: null,
        },
      ],
    });
  });
});
