/// <reference types="../../../../declarations/global" />

export { default as easyViewSvg } from "./basic-bricks.easy-view.svg";
export { default as microViewSvg } from "./basic-bricks.micro-view.svg";
export { default as generalButtonSvg } from "./basic-bricks.general-button.svg";
export { default as foldBrickV2Svg } from "./basic-bricks.fold-brick-v2.svg";
export { default as generalCardSvg } from "./basic-bricks.general-card.svg";
export { default as generalCustomButtonsSvg } from "./basic-bricks.general-custom-buttons.svg";
export { default as generalDrawerSvg } from "./basic-bricks.general-drawer.svg";
export { default as generalModalSvg } from "./basic-bricks.general-modal.svg";
export { default as gridLayoutSvg } from "./basic-bricks.grid-layout.svg";
export { default as pageTitleSvg } from "./basic-bricks.page-title.svg";
export { default as popoverContainerSvg } from "./basic-bricks.popover-container.svg";
export { default as advancedListContainerSvg } from "./basic-bricks.advanced-list-container.svg";
export { default as listContainerSvg } from "./basic-bricks.list-container.svg";
export { default as exportJsonFileSvg } from "./basic-bricks.export-json-file.svg";
export { default as flexLayoutSvg } from "./basic-bricks.flex-layout.svg";
export { default as generalAnchorSvg } from "./basic-bricks.general-anchor.svg";
export { default as generalHotkeysSvg } from "./basic-bricks.general-hotkeys.svg";
export { default as generalNotificationSvg } from "./basic-bricks.general-notification.svg";
export { default as generalTimerSvg } from "./basic-bricks.general-timer.svg";
export { default as generalTitleSvg } from "./basic-bricks.general-title.svg";
export { default as indexCardSvg } from "./basic-bricks.index-card.svg";
export { default as menuBarSvg } from "./basic-bricks.menu-bar .svg";
export { default as mutipleColumnsCardSvg } from "./basic-bricks.multiple-columns-card.svg";
export { default as printButtonSvg } from "./basic-bricks.print-button.svg";
export { default as redirectToSvg } from "./basic-bricks.redirect-to.svg";
export { default as scriptBrickSvg } from "./basic-bricks.script-brick.svg";
export { default as subMenuSvg } from "./basic-bricks.sub-menu.svg";
export { default as subMenuFilterSvg } from "./basic-bricks.sub-menu-filter.svg";
export { default as transformAgentSvg } from "./basic-bricks.transform-agent.svg";
