import "./i18n";
// !Lazy: import "./brick-book";
// !Lazy: import "./doc-book";
// !Lazy: import "./providers-of-brick-story";
import "./provider-providers-sub-menu";
import "./provider-provider-doc";
// !Lazy: import "./brick-debug";
import "./bricks-of-providers";
// !Lazy: import "./provider-doc";
// !Lazy: import "./data-providers/GetStatistics";
import "./data-providers/GetIconList";
import "./data-providers/GetCssVariables";
import "./brick-colors";
import "./data-providers/GetProvidersList";
import "./data-providers/GetBricksDoc";
import "./illustration-card";
import "./data-providers/GetIllustrations";
import "./lazy-bricks";
import "./provider-group-list";
import "./provider-group-menu";
