import "./i18n";
import "./data-providers/ScanBricksAndTemplates";
import "./data-providers/GenerateBricksBasedOnModel";
import "./data-providers/GetAttrBrickConf";
import "./data-providers/GenerateTemplateProxy";
import "./custom-processors/buildStoryboard";
import "./custom-processors/getBrickConfig";
import "./custom-processors/routeTree";
import "./data-providers/BuilderGraphData";
import "./data-providers/AddStoryboardNodeAndReorder";
import "./data-providers/MoveStoryboardNodeAndReorder";
// !Lazy: import "./builder-container";
import "./data-providers/GetAllProviders";
import "./data-providers/GetBrickLibrary";
import "./data-providers/StoryboardAssembly";
import "./data-providers/ScanI18nInStoryboard";
import "./data-providers/FindReferencesOfTemplate";
import "./data-providers/ApplyStoryboardSnippet";
// !Lazy: import "./search-tree";
import "./lazy-bricks";
import "./data-providers/ScanFunctionsInStoryboard";
import "./data-providers/BuildProjectOfTemplates";
import "./data-providers/getStoriesJson";
import "./events-editor";
// !Lazy: import "./event-config-form";
import "./custom-processors/getProcessedEvents";
import "./custom-processors/covertEventToFormValue";
import "./custom-processors/covertFormValueToEvent";
import "./custom-processors/covertUseResolvesToFormValue";
import "./custom-processors/covertFormValueToUseResolves";
import "./function-debugger-sidebar";
import "./function-debugger-toolbar";
import "./function-debugger-store";
import "./function-debugger-statusbar";
import "./data-providers/RunStoryboardFunctionTests";
import "./data-providers/GetUnusedImages";
import "./data-providers/LintStoryboard";
import "./data-providers/CreateThemePage";
import "./data-providers/DeleteThemePage";
import "./data-providers/BuildProjectOfThemeTemplate";
import "./data-providers/ExperimentalExportThemeTemplate";
import "./data-providers/ApplyThemeTemplate";
import "./data-providers/ApplyThemePage";
import "./data-providers/GetProviderOfStoryboard";
import "./data-providers/GetTypeDeclarations";
import "./data-providers/GetTypeDeclarationsOfFn";
import "./custom-processors/getWorkbenchRouteTree";
// !Lazy: import "./workbench-action";
// !Lazy: import "./workbench-sidebar";
// !Lazy: import "./workbench-pane";
// !Lazy: import "./workbench-tree";
// !Lazy: import "./workbench-store";
// !Lazy: import "./workbench-brick-tree";
import "./preview-container";
