import {
  processRefItemData,
  processRefItemInitValue,
  checkRequired,
  extractRefType,
  getFlattenFields,
} from "./refItem";

describe("refItem processor", () => {
  describe("processRefItemInitValue", () => {
    it("should work", () => {
      const result = processRefItemInitValue("Host.ip");
      expect(result).toEqual({
        name: "Host",
        field: "ip",
      });

      const result2 = processRefItemInitValue();
      expect(result2).toEqual({
        name: undefined,
        field: undefined,
      });
    });
  });

  describe("processRefItemData", () => {
    it("should work", () => {
      const result = processRefItemData({
        name: "Host",
        field: "ip",
      });
      expect(result).toEqual("Host.ip");

      const result2 = processRefItemData();
      expect(result2).toEqual("undefined.undefined");
    });
  });

  describe("checkRequired", () => {
    it("should work", async () => {
      await expect(checkRequired({}, "Host.ip")).resolves.toEqual(undefined);

      await expect(checkRequired({}, "")).rejects.toThrow(
        "flow-builder:REF_VALIDATE_REQUIRED_MSG"
      );
    });
  });

  describe("extractRefType", () => {
    it("should work", () => {
      expect(extractRefType("Admin.*")).toEqual("Admin");

      expect(extractRefType()).toEqual("");
    });
  });

  describe("getFlattenFields", () => {
    it.each([
      [
        [
          {
            ref: "EmissionSource.instanceId",
          },
          {
            ref: "EmissionSource.name",
          },
          {
            ref: "EmissionSource.emissionSourceType",
          },
          {
            ref: "EmissionSource.ghgs",
          },
          {
            ref: "EmissionSource.emissionActivity",
          },
          {
            ref: "EmissionSource.emissionSourceID",
          },
          {
            deprecated: false,
            description: "activityData",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "单位",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "instanceId",
                    enum: [],
                    fields: [],
                    name: "instanceId",
                    ref: "",
                    type: "instance_id",
                    validate: null,
                  },
                  {
                    deprecated: false,
                    description: "name",
                    enum: [],
                    fields: [],
                    name: "name",
                    ref: "",
                    type: "string",
                    validate: null,
                  },
                ],
                name: "unit",
                ref: "",
                type: "object",
                validate: null,
              },
            ],
            name: "activityData",
            ref: "",
            type: "object",
            validate: null,
          },
          {
            deprecated: false,
            description: "数据上报",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "填报人",
                enum: [],
                fields: [],
                name: "reporter",
                ref: "",
                type: "string",
                validate: null,
              },
              {
                deprecated: false,
                description: "报送频率",
                enum: [],
                fields: [],
                name: "reportFreq",
                ref: "",
                type: "string",
                validate: null,
              },
              {
                deprecated: false,
                description: "报送时限",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "次月开始日",
                    enum: [],
                    fields: [],
                    name: "min",
                    ref: "",
                    type: "int",
                    validate: null,
                  },
                  {
                    deprecated: false,
                    description: "次月结束日",
                    enum: [],
                    fields: [],
                    name: "max",
                    ref: "",
                    type: "int",
                    validate: null,
                  },
                ],
                name: "reportTimer",
                ref: "",
                type: "object",
                validate: null,
              },
              {
                deprecated: false,
                description: "报送类型",
                enum: ["排放数据填报"],
                fields: [],
                name: "reportType",
                ref: "",
                type: "string",
                validate: null,
              },
            ],
            name: "reportion",
            ref: "",
            type: "object",
            validate: null,
          },
          {
            deprecated: false,
            description: "organization",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validate: null,
              },
              {
                deprecated: false,
                description: "name",
                enum: [],
                fields: [],
                name: "name",
                ref: "",
                type: "string",
                validate: null,
              },
            ],
            name: "organization",
            ref: "",
            type: "object",
            validate: null,
          },
          {
            deprecated: false,
            description: "boundary",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validate: null,
              },
              {
                deprecated: false,
                description: "name",
                enum: [],
                fields: [],
                name: "name",
                ref: "",
                type: "string",
                validate: null,
              },
            ],
            name: "boundary",
            ref: "",
            type: "object",
            validate: null,
          },
        ],
        [
          {
            fields: [
              {
                deprecated: false,
                description: "instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "排放源名称",
                enum: [],
                fields: [],
                name: "name",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "排放源类型",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "type",
                    enum: [],
                    fields: [],
                    name: "type",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "instanceId",
                    enum: [],
                    fields: [],
                    name: "instanceId",
                    ref: "",
                    type: "instance_id",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "category",
                    enum: [],
                    fields: [],
                    name: "category",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "classify",
                    enum: [],
                    fields: [],
                    name: "classify",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                ],
                name: "emissionSourceType",
                ref: "",
                type: "object",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "温室气体",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "ghg instanceId",
                    enum: [],
                    fields: [],
                    name: "instanceId",
                    ref: "",
                    type: "instance_id",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "温室气体名称",
                    enum: [],
                    fields: [],
                    name: "ghg",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "化学式",
                    enum: [],
                    fields: [],
                    name: "chemicalFormula",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                ],
                name: "ghgs",
                ref: "",
                type: "object[]",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "排放活动类型",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "test id",
                    enum: [],
                    fields: [],
                    name: "testId",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                ],
                name: "emissionActivity",
                ref: "",
                type: "object",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "排放源ID",
                enum: [],
                fields: [],
                name: "emissionSourceID",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "活动数据",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "数据单位",
                    enum: [],
                    fields: [
                      {
                        deprecated: false,
                        description: "instanceId",
                        enum: [],
                        fields: [],
                        name: "instanceId",
                        ref: "",
                        type: "instance_id",
                        validateRule: null,
                      },
                      {
                        deprecated: false,
                        description: "单位名称",
                        enum: [],
                        fields: [],
                        name: "unit",
                        ref: "",
                        type: "string",
                        validateRule: null,
                      },
                    ],
                    name: "unit",
                    ref: "",
                    type: "object",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "活动数据范围",
                    enum: [],
                    fields: [
                      {
                        deprecated: false,
                        description: "最小值",
                        enum: [],
                        fields: [],
                        name: "min",
                        ref: "",
                        type: "float",
                        validateRule: null,
                      },
                      {
                        deprecated: false,
                        description: "最大值",
                        enum: [],
                        fields: [],
                        name: "max",
                        ref: "",
                        type: "float",
                        validateRule: null,
                      },
                    ],
                    name: "range",
                    ref: "",
                    type: "object",
                    validateRule: null,
                  },
                ],
                name: "activityData",
                ref: "",
                type: "object",
                validateRule: null,
              },
            ],
            name: "EmissionSource",
          },
        ],
        [
          {
            deprecated: false,
            description: "instanceId",
            enum: [],
            fields: [],
            name: "instanceId",
            ref: "",
            type: "instance_id",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "排放源名称",
            enum: [],
            fields: [],
            name: "name",
            ref: "",
            type: "string",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "排放源类型",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "type",
                enum: [],
                fields: [],
                name: "type",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "category",
                enum: [],
                fields: [],
                name: "category",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "classify",
                enum: [],
                fields: [],
                name: "classify",
                ref: "",
                type: "string",
                validateRule: null,
              },
            ],
            name: "emissionSourceType",
            ref: "",
            type: "object",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "温室气体",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "ghg instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "温室气体名称",
                enum: [],
                fields: [],
                name: "ghg",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "化学式",
                enum: [],
                fields: [],
                name: "chemicalFormula",
                ref: "",
                type: "string",
                validateRule: null,
              },
            ],
            name: "ghgs",
            ref: "",
            type: "object[]",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "排放活动类型",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "test id",
                enum: [],
                fields: [],
                name: "testId",
                ref: "",
                type: "string",
                validateRule: null,
              },
            ],
            name: "emissionActivity",
            ref: "",
            type: "object",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "排放源ID",
            enum: [],
            fields: [],
            name: "emissionSourceID",
            ref: "",
            type: "string",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "activityData",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "单位",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "instanceId",
                    enum: [],
                    fields: [],
                    name: "instanceId",
                    ref: "",
                    type: "instance_id",
                    validate: null,
                  },
                  {
                    deprecated: false,
                    description: "name",
                    enum: [],
                    fields: [],
                    name: "name",
                    ref: "",
                    type: "string",
                    validate: null,
                  },
                ],
                name: "unit",
                ref: "",
                type: "object",
                validate: null,
              },
            ],
            name: "activityData",
            ref: "",
            type: "object",
            validate: null,
          },
          {
            deprecated: false,
            description: "数据上报",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "填报人",
                enum: [],
                fields: [],
                name: "reporter",
                ref: "",
                type: "string",
                validate: null,
              },
              {
                deprecated: false,
                description: "报送频率",
                enum: [],
                fields: [],
                name: "reportFreq",
                ref: "",
                type: "string",
                validate: null,
              },
              {
                deprecated: false,
                description: "报送时限",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "次月开始日",
                    enum: [],
                    fields: [],
                    name: "min",
                    ref: "",
                    type: "int",
                    validate: null,
                  },
                  {
                    deprecated: false,
                    description: "次月结束日",
                    enum: [],
                    fields: [],
                    name: "max",
                    ref: "",
                    type: "int",
                    validate: null,
                  },
                ],
                name: "reportTimer",
                ref: "",
                type: "object",
                validate: null,
              },
              {
                deprecated: false,
                description: "报送类型",
                enum: ["排放数据填报"],
                fields: [],
                name: "reportType",
                ref: "",
                type: "string",
                validate: null,
              },
            ],
            name: "reportion",
            ref: "",
            type: "object",
            validate: null,
          },
          {
            deprecated: false,
            description: "organization",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validate: null,
              },
              {
                deprecated: false,
                description: "name",
                enum: [],
                fields: [],
                name: "name",
                ref: "",
                type: "string",
                validate: null,
              },
            ],
            name: "organization",
            ref: "",
            type: "object",
            validate: null,
          },
          {
            deprecated: false,
            description: "boundary",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validate: null,
              },
              {
                deprecated: false,
                description: "name",
                enum: [],
                fields: [],
                name: "name",
                ref: "",
                type: "string",
                validate: null,
              },
            ],
            name: "boundary",
            ref: "",
            type: "object",
            validate: null,
          },
        ],
      ],
      [
        [
          {
            ref: "EmissionSource.*",
          },
        ],
        [
          {
            fields: [
              {
                deprecated: false,
                description: "instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "排放源名称",
                enum: [],
                fields: [],
                name: "name",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "排放源类型",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "type",
                    enum: [],
                    fields: [],
                    name: "type",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "instanceId",
                    enum: [],
                    fields: [],
                    name: "instanceId",
                    ref: "",
                    type: "instance_id",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "category",
                    enum: [],
                    fields: [],
                    name: "category",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "classify",
                    enum: [],
                    fields: [],
                    name: "classify",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                ],
                name: "emissionSourceType",
                ref: "",
                type: "object",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "温室气体",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "ghg instanceId",
                    enum: [],
                    fields: [],
                    name: "instanceId",
                    ref: "",
                    type: "instance_id",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "温室气体名称",
                    enum: [],
                    fields: [],
                    name: "ghg",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "化学式",
                    enum: [],
                    fields: [],
                    name: "chemicalFormula",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                ],
                name: "ghgs",
                ref: "",
                type: "object[]",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "排放活动类型",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "test id",
                    enum: [],
                    fields: [],
                    name: "testId",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                ],
                name: "emissionActivity",
                ref: "",
                type: "object",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "排放源ID",
                enum: [],
                fields: [],
                name: "emissionSourceID",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "活动数据",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "数据单位",
                    enum: [],
                    fields: [
                      {
                        deprecated: false,
                        description: "instanceId",
                        enum: [],
                        fields: [],
                        name: "instanceId",
                        ref: "",
                        type: "instance_id",
                        validateRule: null,
                      },
                      {
                        deprecated: false,
                        description: "单位名称",
                        enum: [],
                        fields: [],
                        name: "unit",
                        ref: "",
                        type: "string",
                        validateRule: null,
                      },
                    ],
                    name: "unit",
                    ref: "",
                    type: "object",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "活动数据范围",
                    enum: [],
                    fields: [
                      {
                        deprecated: false,
                        description: "最小值",
                        enum: [],
                        fields: [],
                        name: "min",
                        ref: "",
                        type: "float",
                        validateRule: null,
                      },
                      {
                        deprecated: false,
                        description: "最大值",
                        enum: [],
                        fields: [],
                        name: "max",
                        ref: "",
                        type: "float",
                        validateRule: null,
                      },
                    ],
                    name: "range",
                    ref: "",
                    type: "object",
                    validateRule: null,
                  },
                ],
                name: "activityData",
                ref: "",
                type: "object",
                validateRule: null,
              },
            ],
            name: "EmissionSource",
          },
        ],
        [
          {
            deprecated: false,
            description: "instanceId",
            enum: [],
            fields: [],
            name: "instanceId",
            ref: "",
            type: "instance_id",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "排放源名称",
            enum: [],
            fields: [],
            name: "name",
            ref: "",
            type: "string",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "排放源类型",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "type",
                enum: [],
                fields: [],
                name: "type",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "category",
                enum: [],
                fields: [],
                name: "category",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "classify",
                enum: [],
                fields: [],
                name: "classify",
                ref: "",
                type: "string",
                validateRule: null,
              },
            ],
            name: "emissionSourceType",
            ref: "",
            type: "object",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "温室气体",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "ghg instanceId",
                enum: [],
                fields: [],
                name: "instanceId",
                ref: "",
                type: "instance_id",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "温室气体名称",
                enum: [],
                fields: [],
                name: "ghg",
                ref: "",
                type: "string",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "化学式",
                enum: [],
                fields: [],
                name: "chemicalFormula",
                ref: "",
                type: "string",
                validateRule: null,
              },
            ],
            name: "ghgs",
            ref: "",
            type: "object[]",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "排放活动类型",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "test id",
                enum: [],
                fields: [],
                name: "testId",
                ref: "",
                type: "string",
                validateRule: null,
              },
            ],
            name: "emissionActivity",
            ref: "",
            type: "object",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "排放源ID",
            enum: [],
            fields: [],
            name: "emissionSourceID",
            ref: "",
            type: "string",
            validateRule: null,
          },
          {
            deprecated: false,
            description: "活动数据",
            enum: [],
            fields: [
              {
                deprecated: false,
                description: "数据单位",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "instanceId",
                    enum: [],
                    fields: [],
                    name: "instanceId",
                    ref: "",
                    type: "instance_id",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "单位名称",
                    enum: [],
                    fields: [],
                    name: "unit",
                    ref: "",
                    type: "string",
                    validateRule: null,
                  },
                ],
                name: "unit",
                ref: "",
                type: "object",
                validateRule: null,
              },
              {
                deprecated: false,
                description: "活动数据范围",
                enum: [],
                fields: [
                  {
                    deprecated: false,
                    description: "最小值",
                    enum: [],
                    fields: [],
                    name: "min",
                    ref: "",
                    type: "float",
                    validateRule: null,
                  },
                  {
                    deprecated: false,
                    description: "最大值",
                    enum: [],
                    fields: [],
                    name: "max",
                    ref: "",
                    type: "float",
                    validateRule: null,
                  },
                ],
                name: "range",
                ref: "",
                type: "object",
                validateRule: null,
              },
            ],
            name: "activityData",
            ref: "",
            type: "object",
            validateRule: null,
          },
        ],
      ],
    ])("should work", (fields, importModelDefinition, result) => {
      expect(getFlattenFields(fields, importModelDefinition)).toEqual(result);
    });
  });
});
