import "./i18n";
import "./general-form";
import "./general-input";
import "./general-select";
import "./general-date-picker";
import "./general-time-picker";
import "./cmdb-instance-select";
import "./general-input-number";
import "./general-checkbox";
import "./general-radio";
import "./general-buttons";
import "./general-textarea";
// !Lazy: import "./general-modal";
// !Lazy: import "./cmdb-instance-select-panel";
// !Lazy: import "./user-or-user-group-select";
// !Lazy: import "./crontab-input";
import "./general-switch";
import "./time-range-picker";
import "./general-auto-complete";
import "./input-with-unit";
import "./upload-img";
// !Lazy: import "./general-form-item";
import "./inform-methods-form";
import "./icon-select";
import "./dynamic-form-input-item";
// !Lazy: import "./general-structs-form-item";
import "./general-cascader";
import "./dynamic-form-item";
import "./general-slide";
import "./cmdb-object-attr-value";
// !Lazy: import "./advance-setting";
import "./custom-templates/tpl-cmdb-object-attr-add";
import "./tree-select";
import "./form-modal";
import "./upload-files";
import "./dynamic-user-select-item";
import "./upload-files-v2";
import "./lazy-bricks";
